# =============================================================================
# movies-parser Argo Rollout - Blue/Green Deployment Strategy
# =============================================================================
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: movies-parser
  namespace: movies-app
  labels:
    app: movies-parser
    app.kubernetes.io/name: movies-parser
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: movies-parser
  template:
    metadata:
      labels:
        app: movies-parser
        app.kubernetes.io/name: movies-parser
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: movies-parser
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: movies-app-config
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
  strategy:
    blueGreen:
      activeService: movies-parser-active
      previewService: movies-parser-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      previewReplicaCount: 1
---
apiVersion: v1
kind: Service
metadata:
  name: movies-parser-active
  namespace: movies-app
  labels:
    app: movies-parser
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: movies-parser
---
apiVersion: v1
kind: Service
metadata:
  name: movies-parser-preview
  namespace: movies-app
  labels:
    app: movies-parser
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: movies-parser
