# =============================================================================
# ArgoCD Application - Movies App (Production Environment)
# Manual sync required for production safety
# =============================================================================
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies-app-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: movies-app
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ahmedfawzy21/gitops-mainfests.git
    targetRevision: main
    path: overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: movies-app

  # Production: Manual sync only (no auto-sync)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /status
